Automate PyPi uploads on release
HumanCompatibleAI/imitation pull request #489
Opened 2022-07-24 00:35 UTC by AdamGleave

2022-07-24 10:33 UTC, Rocamonde commented on setup.py
> +        "chai-sacred>=0.8.3",
Lol this is bold but effective for now. It is a bit worrisome that the devs have not been updating the release on PyPI regularly.

2022-07-24 11:18 UTC, Rocamonde commented
LGTM. Now we'd have to create a release draft, and make sure to add useful information in the release notes

2022-07-25 18:05 UTC, norabelrose requested changes
This looks good to me except that the docs seem to be failing to build in the CI because the readthedocs build is still using Python 3.7. This PR uses `importlib.metadata` which was added in Python 3.8. We should probably change `readthedocs.yml` to Python 3.8 to fix this?

2022-07-25 18:09 UTC, Rocamonde commented
> This looks good to me except that the docs seem to be failing to build in the CI because the readthedocs build is still using Python 3.7. This PR uses `importlib.metadata` which was added in Python 3.8. We should probably change `readthedocs.yml` to Python 3.8 to fix this?

This is done in #484, but this should probably get merged first, so I agree with this.

2022-07-25 18:14 UTC, AdamGleave commented
Fixed doc building issue now by bumping to 3.8.

2022-07-25 19:00 UTC, AdamGleave commented
Windows tests failing are flaky and will be fixed in https://github.com/DLR-RM/stable-baselines3/pull/979 -- we were previously hotfixing to that, but PyPI won't allow dependencies on specific GH issues.

I'm going to just skip these tests on Windows for now as a workaround.

2022-07-26 21:01 UTC, norabelrose approved these changes
LGTM

2022-07-26 21:01 UTC, merged

2022-07-26 21:20 UTC, AdamGleave commented
This automation failed after merge for the v0.3.0 tag because our Test PyPI instance had a spurious v0.3.0 package. This problem should go away once we make the next minor release.