Reward-net-docs
HumanCompatibleAI/imitation pull request #750
Opened 2023-07-07 20:15 UTC by levmckinney

## Description
Adds basic documentation on reward networks. Resolves #714 and by extension #698.

## Testing
* Only documentation changes

## TODO
* [ ] switch all totorials to using `predict_processed` instead of `predict` in when using the reward network to train a policy.

2023-07-10 11:20 UTC, ernestum requested changes
This is clearly written and after reading it I feel that I got a good understanding about thow the reward networks are used and what the design choices were when implementing them.

2023-07-10 11:20 UTC, ernestum commented on docs/tutorials/reward_networks.rst
> +Imitation learning algorithms should converge to a reward function that will theoretically induce the optimal/soft optimal policy. However, these reward functions may not always be well suited for tr
Maybe link to a definition of "soft optimal"?

2023-07-10 11:20 UTC, ernestum commented on docs/tutorials/reward_networks.rst
> +
Does not render correctly in sphinx. Try dashes and indentation an extra newline?

What doe you mean by "always active"? Why should they not be always active?

2023-07-10 11:20 UTC, ernestum commented on docs/tutorials/reward_networks.rst
> +
This note confuses me. You seem to say that the NromalizedRwardNet Wrapper on a running estimate but then what you describe below *does* sound like a running estimate.

Also I think the last sentence might have one "on" too many.

2023-07-10 11:20 UTC, ernestum commented on docs/tutorials/reward_networks.rst
> +
On the first pass reading it was not clear here whether `th.save(reward_net, path)` will also save the wrappers and if `th.load(path)` would restore them. I then read the code to clarify and came back to the description to read it a second time. Then it was clear.

Maybe you can help (quick) understanding by adding to the first sentence:

"Reward networks and **their wrappers** are serialized simply by calling ..."

and 

"to laod the raw reward network **without wrappers applied**, we can simply call ..."

2023-07-12 21:13 UTC, levmckinney commented on src/imitation/rewards/reward_nets.py
> +            # state spaces with more than one axis?
I'm just being dumb and mis read this code its fine.

2023-07-14 08:45 UTC, merged